matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libx11-dev
            - libxext-dev
            - libxss-dev
            - libxkbfile-dev
    - os: osx
      osx_image: xcode11

language: node_js
# Handle git submodules yourself
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    else
      sed -i '' 's/git@github.com:/https:\/\/github.com\//' .gitmodules # macOS
    fi
  - git submodule update --init --recursive
install:
  - echo do nothing
before_script:
  - npx lerna bootstrap
  - npm install node-sass -g
script:
  - npm run test
  - travis_wait 30 npm run build
cache: npm

branches:
  except:
    - i18n
    - l10n_master
    - l10n_develop
