environment:
  APPVEYOR_CACHE_SKIP_RESTORE: true

version: 5.4.1-beta.1.{build}

install:
  - git submodule update --init --recursive
  - ps: Install-Product node 10
  - npx lerna bootstrap

cache:
  - '%APPDATA%\npm-cache'

before_build:
  - npm run lint
  - cmd: set NODE_ENV=production

build_script:
  - npm run build

branches:
  except:
    - i18n
    - l10n_master
    - l10n_develop

for:
  - branches:
      only:
        - master
        - /v\d*\.\d*\.\d*/
        - /v\d*\.\d*\.\d*-beta\.\d*/
    artifacts:
      - path: out\*.exe
      - path: out\*.yml
